/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import componentes.MiPanel;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ESTUDIANTE
 */
public class Main extends javax.swing.JFrame {
    private int posX = 50, posY = 50;
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        MiPanel p = new MiPanel();
        p.setSize(pAreaCliente.getSize());
        p.setBorder(BorderFactory.createEtchedBorder());
        p.setBackground(Color.white);
        
        pAreaCliente.add(p);
        pAreaCliente.revalidate();
        pAreaCliente.repaint();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        pAreaCliente = new javax.swing.JPanel();
        Guardar = new javax.swing.JButton();
        Cargar = new javax.swing.JButton();
        GenerarExpresion = new javax.swing.JButton();
        GenerarCircuito = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        tablaV = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AND = new javax.swing.JMenuItem();
        OR = new javax.swing.JMenuItem();
        NOT = new javax.swing.JMenuItem();
        Xor = new javax.swing.JMenuItem();
        Switch = new javax.swing.JMenuItem();
        Led = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jMenu6.setText("File");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar2.add(jMenu7);

        jMenuItem3.setText("jMenuItem3");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        pAreaCliente.setBackground(new java.awt.Color(255, 255, 255));
        pAreaCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pAreaClienteLayout = new javax.swing.GroupLayout(pAreaCliente);
        pAreaCliente.setLayout(pAreaClienteLayout);
        pAreaClienteLayout.setHorizontalGroup(
            pAreaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 953, Short.MAX_VALUE)
        );
        pAreaClienteLayout.setVerticalGroup(
            pAreaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Cargar.setText("Cargar");
        Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarActionPerformed(evt);
            }
        });

        GenerarExpresion.setText("Genar Expresion");
        GenerarExpresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarExpresionActionPerformed(evt);
            }
        });

        GenerarCircuito.setText("Genar Circuito");
        GenerarCircuito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarCircuitoActionPerformed(evt);
            }
        });

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        tablaV.setText("Genar Tabla V");
        tablaV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablaVActionPerformed(evt);
            }
        });

        jMenu1.setText("Componentes");

        AND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AND.jpg"))); // NOI18N
        AND.setText("AND");
        AND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANDActionPerformed(evt);
            }
        });
        jMenu1.add(AND);

        OR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/OR.jpg"))); // NOI18N
        OR.setText("OR");
        OR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ORActionPerformed(evt);
            }
        });
        jMenu1.add(OR);

        NOT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NOT.jpg"))); // NOI18N
        NOT.setText("NOT");
        NOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOTActionPerformed(evt);
            }
        });
        jMenu1.add(NOT);

        Xor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/XOR.png"))); // NOI18N
        Xor.setText("XOR");
        Xor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XorActionPerformed(evt);
            }
        });
        jMenu1.add(Xor);

        Switch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SWITCH.png"))); // NOI18N
        Switch.setText("Switch");
        Switch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwitchActionPerformed(evt);
            }
        });
        jMenu1.add(Switch);

        Led.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LED.png"))); // NOI18N
        Led.setText("Led");
        Led.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LedActionPerformed(evt);
            }
        });
        jMenu1.add(Led);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GenerarExpresion)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(limpiar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GenerarCircuito, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cargar)
                            .addComponent(Guardar)))
                    .addComponent(tablaV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(pAreaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pAreaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cargar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GenerarExpresion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tablaV)
                .addGap(7, 7, 7)
                .addComponent(GenerarCircuito)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here
    }//GEN-LAST:event_formMouseClicked

    private void NOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOTActionPerformed

        MiPanel p = (MiPanel) pAreaCliente.getComponent(0);
        p.agregarComponente(posX, posY, "NOT", 1);
        actualizarPosicion();
        p.repaint();
    }//GEN-LAST:event_NOTActionPerformed

    private void ORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ORActionPerformed
        MiPanel p = (MiPanel) pAreaCliente.getComponent(0);
        p.agregarComponente(posX, posY, "OR", 2);
        actualizarPosicion();
        p.repaint();
    }//GEN-LAST:event_ORActionPerformed

    private void ANDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANDActionPerformed
        MiPanel p = (MiPanel) pAreaCliente.getComponent(0);
        p.agregarComponente(posX, posY, "AND", 2);
        actualizarPosicion();
        p.repaint();
    }//GEN-LAST:event_ANDActionPerformed

    private void SwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwitchActionPerformed
        MiPanel p = (MiPanel) pAreaCliente.getComponent(0);
        p.agregarComponente(posX, posY, "SWITCH", 1);
        actualizarPosicion();
        p.repaint();
    }//GEN-LAST:event_SwitchActionPerformed

    private void LedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LedActionPerformed
        MiPanel p = (MiPanel) pAreaCliente.getComponent(0);
        p.agregarComponente(posX, posY, "LED", 1);
        actualizarPosicion();
        p.repaint();
    }//GEN-LAST:event_LedActionPerformed

    private void XorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XorActionPerformed
    MiPanel p = (MiPanel) pAreaCliente.getComponent(0);
    p.agregarComponente(posX, posY, "XOR", 2); // Llamamos a agregar la compuerta
    actualizarPosicion();
    p.repaint();
    }//GEN-LAST:event_XorActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
    MiPanel p = (MiPanel) pAreaCliente.getComponent(0);
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Guardar Circuito");
    
    int userSelection = fileChooser.showSaveDialog(this);
    
    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File archivo = fileChooser.getSelectedFile();
        p.guardarCircuitoEnDisco(archivo.getAbsolutePath());
    }
    }//GEN-LAST:event_GuardarActionPerformed

    private void CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarActionPerformed
    MiPanel p = (MiPanel) pAreaCliente.getComponent(0);
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Cargar Circuito");

    int userSelection = fileChooser.showOpenDialog(this);

    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File archivo = fileChooser.getSelectedFile();
        p.cargarCircuitoDesdeDisco(archivo.getAbsolutePath());
    }
    }//GEN-LAST:event_CargarActionPerformed

    private void GenerarExpresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarExpresionActionPerformed
        MiPanel p = (MiPanel) pAreaCliente.getComponent(0);
        p.mostrarExpresiones();
    }//GEN-LAST:event_GenerarExpresionActionPerformed

    private void GenerarCircuitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarCircuitoActionPerformed
        MiPanel p = (MiPanel) pAreaCliente.getComponent(0);
        p.generarDesdeExpresion();
        p.repaint();
    }//GEN-LAST:event_GenerarCircuitoActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        MiPanel p = (MiPanel) pAreaCliente.getComponent(0);
        p.limpiarCircuito();
        
    }//GEN-LAST:event_limpiarActionPerformed

    private void tablaVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablaVActionPerformed
        MiPanel p = (MiPanel) pAreaCliente.getComponent(0);
        p.mostrarTablaDesdeExpresion();
    }//GEN-LAST:event_tablaVActionPerformed

    /**
     * @param args the command line arguments
     */
    private void actualizarPosicion() {
        posX += 85;
        if (posX > pAreaCliente.getWidth() - 60) { 
            posX = 50;
            posY += 80;
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AND;
    private javax.swing.JButton Cargar;
    private javax.swing.JButton GenerarCircuito;
    private javax.swing.JButton GenerarExpresion;
    private javax.swing.JButton Guardar;
    private javax.swing.JMenuItem Led;
    private javax.swing.JMenuItem NOT;
    private javax.swing.JMenuItem OR;
    private javax.swing.JMenuItem Switch;
    private javax.swing.JMenuItem Xor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JButton limpiar;
    private javax.swing.JPanel pAreaCliente;
    private javax.swing.JButton tablaV;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
